added better error handling and debugging for artifact download step

diff --git a/.github/workflows/IntegrationTest.yml b/.github/workflows/IntegrationTest.yml
--- a/.github/workflows/IntegrationTest.yml
+++ b/.github/workflows/IntegrationTest.yml
@@ -64,14 +64,38 @@ jobs:
           base_uri="https://api.github.com"
           repo="${{ github.repository }}"
           artifacts_uri="$base_uri/repos/$repo/actions/artifacts"
-          token="${{ steps.generate_token.outputs.token }}"
-          api_response=$(curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $token" -H "X-GitHub-Api-Version: 2022-11-28" "$artifacts_uri")
-          sorted_artifacts=$(echo "$api_response" | jq --arg name "terraformstatefile" '.artifacts | map(select(.name == $name)) | sort_by(.created_at) | reverse')
-          most_recent=$(echo "$sorted_artifacts" | jq -r 'first(.[])')
-          archive_download_url=$(echo "$most_recent" | jq -r '.archive_download_url')
-          if [ "$archive_download_url" ]; then
-            curl -s -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $token" -H "X-GitHub-Api-Version: 2022-11-28" "$archive_download_url" -o "${{ github.workspace }}/terraformstatefile.zip"
-            unzip -o "${{ github.workspace }}/terraformstatefile.zip" -d "${{ github.workspace }}/ansible/"
+          token="${{ github.token }}"
+          api_response=$(curl -s -L -w "http_response:%{http_code}" \
+              -H "Authorization: Bearer $token" \
+              "$artifacts_uri")
+          status_code=$(echo "$api_response" | grep -o "http_response:[0-9]\+" | cut -d ':' -f 2)
+
+          if [ "$status_code" -eq 200 ]; then
+              sorted_artifacts=$(curl -s -L \
+              -H "Authorization: Bearer $token" \
+              "$artifacts_uri" | jq --arg name "terraformstatefile" '.artifacts | map(select(.name == $name)) | sort_by(.created_at) | reverse')
+              most_recent=$(echo "$sorted_artifacts" | jq -r 'first(.[])')
+              archive_download_url=$(echo "$most_recent" | jq -r '.archive_download_url')
+              if [ "$archive_download_url" ]; then
+                  echo "Most recent artifact URI = $archive_download_url"
+                  download=$(curl -s -L -w "http_response:%{http_code}" \
+                      -H "Authorization: Bearer $token" \
+                      "$archive_download_url" -o "./terraformstatefile.zip")
+                  status_code=$(echo "$download" | grep -o "http_response:[0-9]\+" | cut -d ':' -f 2)
+                  if [ "$status_code" -eq 200 ]; then
+                      echo "Statefile artifact downloaded! Extracting contents..."
+                      unzip -o "./terraformstatefile.zip" -d "../../ansible/"
+                  else
+                      echo "Error: $status_code"
+                      exit 1
+                  fi
+              else
+                  echo "No artifact found!"
+                  exit 0
+              fi
+          else
+              echo "Error: $status_code"
+              exit 1
           fi
       - name: Terraform Init
         id: init
